INSERT INTO [dbo].[MenuItem] ([ItemID], [naam], [prijs], [aantal]) VALUES (1, N'Steak tartaar met truffelmayonaisse', 7.5, 11)
INSERT INTO [dbo].[Menu_Item] ([ItemID], [naam], [prijs], [aantal]) VALUES (2, N'Paté van fazant met monegaskische uitjes', 8.5, 15)
INSERT INTO [dbo].[Menu_Item] ([ItemID], [naam], [prijs], [aantal]) VALUES (3, N'Provençaalse vissoep met rouille, oude kaas en croutons', 6.5, 20)
INSERT INTO [dbo].[Menu_Item] ([ItemID], [naam], [prijs], [aantal]) VALUES (4, N'Hertenstoofpotje met rode kool ', 12.5, 30)
INSERT INTO [dbo].[Menu_Item] ([ItemID], [naam], [prijs], [aantal]) VALUES (5, N'Gebakken kabeljauw met curry-sabayon', 14.5, 20)
INSERT INTO [dbo].[Menu_Item] ([ItemID], [naam], [prijs], [aantal]) VALUES (6, N'Linguini met paddestoelen saus', 13.5, 25)
INSERT INTO [dbo].[Menu_Item] ([ItemID], [naam], [prijs], [aantal]) VALUES (7, N'Taart van witte chocolade en speculaas met mandarijn', 5.5, 22)
INSERT INTO [dbo].[Menu_Item] ([ItemID], [naam], [prijs], [aantal]) VALUES (8, N'Verse madeleines met vijgen compote en creme patissiermet grand manier', 6.5, 18)
INSERT INTO [dbo].[Menu_Item] ([ItemID], [naam], [prijs], [aantal]) VALUES (9, N'3 soorten boerenkazen met rogge rozijnenbrood', 5, 15)
INSERT INTO [dbo].[Menu_Item] ([ItemID], [naam], [prijs], [aantal]) VALUES (10, N'Kalfstartaar met tonijnmayonaise en gefrituurde mosselen', 8.5, 30)
INSERT INTO [dbo].[Menu_Item] ([ItemID], [naam], [prijs], [aantal]) VALUES (11, N'Paté van fazant met monegaskische uitje', 8.5, 33)
INSERT INTO [dbo].[Menu_Item] ([ItemID], [naam], [prijs], [aantal]) VALUES (12, N'Krab-zalm koekjes met zoetzure-chilisaus', 9, 27)
INSERT INTO [dbo].[Menu_Item] ([ItemID], [naam], [prijs], [aantal]) VALUES (13, N'Provençaalse vissoep met rouille en croutons', 6.5, 15)
INSERT INTO [dbo].[Menu_Item] ([ItemID], [naam], [prijs], [aantal]) VALUES (14, N'Consommé van fazant met bosui en groene kruiden', 7.5, 35)
INSERT INTO [dbo].[Menu_Item] ([ItemID], [naam], [prijs], [aantal]) VALUES (15, N'Op de huid gebakken kabeljauw rug filet met curry-sabayon', 17.5, 40)
INSERT INTO [dbo].[Menu_Item] ([ItemID], [naam], [prijs], [aantal]) VALUES (16, N'Gebakken ossenhaas met kalf-jus met roze pepers', 22.5, 10)
INSERT INTO [dbo].[Menu_Item] ([ItemID], [naam], [prijs], [aantal]) VALUES (17, N'Hertenbiefstuk met eigen stoof en rode kool', 25, 23)
INSERT INTO [dbo].[Menu_Item] ([ItemID], [naam], [prijs], [aantal]) VALUES (18, N'Café surprise (Koffie met huisgemaakte bonbons)', 5.5, 17)
INSERT INTO [dbo].[Menu_Item] ([ItemID], [naam], [prijs], [aantal]) VALUES (19, N'Cherry Baby ( Slagroomijs met warme kersen)', 6.5, 26)
INSERT INTO [dbo].[Menu_Item] ([ItemID], [naam], [prijs], [aantal]) VALUES (20, N'Port e Fromage (verschillende kazen met glaasje port)', 7.5, 34)
INSERT INTO [dbo].[Menu_Item] ([ItemID], [naam], [prijs], [aantal]) VALUES (21, N'Spa rood', 2.5, 50)
INSERT INTO [dbo].[Menu_Item] ([ItemID], [naam], [prijs], [aantal]) VALUES (22, N'Spa groen', 2.5, 50)
INSERT INTO [dbo].[Menu_Item] ([ItemID], [naam], [prijs], [aantal]) VALUES (23, N'Coca Cola Light', 2.5, 40)
INSERT INTO [dbo].[Menu_Item] ([ItemID], [naam], [prijs], [aantal]) VALUES (24, N'Coca Cola', 2.5, 40)
INSERT INTO [dbo].[Menu_Item] ([ItemID], [naam], [prijs], [aantal]) VALUES (25, N'Sisi', 2.5, 30)
INSERT INTO [dbo].[Menu_Item] ([ItemID], [naam], [prijs], [aantal]) VALUES (26, N'Tonic', 2.5, 30)
INSERT INTO [dbo].[Menu_Item] ([ItemID], [naam], [prijs], [aantal]) VALUES (27, N'Bitter Lemon', 2.5, 35)
INSERT INTO [dbo].[Menu_Item] ([ItemID], [naam], [prijs], [aantal]) VALUES (28, N'Hertog Jan', 3, 35)
INSERT INTO [dbo].[Menu_Item] ([ItemID], [naam], [prijs], [aantal]) VALUES (29, N'Duvel', 4.5, 20)
INSERT INTO [dbo].[Menu_Item] ([ItemID], [naam], [prijs], [aantal]) VALUES (30, N'Kriek', 4, 40)
INSERT INTO [dbo].[Menu_Item] ([ItemID], [naam], [prijs], [aantal]) VALUES (31, N'Leffe Triple', 4.5, 0)
INSERT INTO [dbo].[Menu_Item] ([ItemID], [naam], [prijs], [aantal]) VALUES (32, N'Witte huiswijn per fles', 28.5, 7)
INSERT INTO [dbo].[Menu_Item] ([ItemID], [naam], [prijs], [aantal]) VALUES (33, N'Witte huiswijn per glas', 6.5, 40)
INSERT INTO [dbo].[Menu_Item] ([ItemID], [naam], [prijs], [aantal]) VALUES (34, N'Rode huiswijn per fles', 32, 20)
INSERT INTO [dbo].[Menu_Item] ([ItemID], [naam], [prijs], [aantal]) VALUES (35, N'Rode huiswijn per glas', 7.5, 50)
INSERT INTO [dbo].[Menu_Item] ([ItemID], [naam], [prijs], [aantal]) VALUES (36, N'Champagne per fles', 50, 10)
INSERT INTO [dbo].[Menu_Item] ([ItemID], [naam], [prijs], [aantal]) VALUES (37, N'Jonge Jenever', 3.5, 40)
INSERT INTO [dbo].[Menu_Item] ([ItemID], [naam], [prijs], [aantal]) VALUES (38, N'Whiskey', 5, 35)
INSERT INTO [dbo].[Menu_Item] ([ItemID], [naam], [prijs], [aantal]) VALUES (39, N'Rum', 4.5, 25)
INSERT INTO [dbo].[Menu_Item] ([ItemID], [naam], [prijs], [aantal]) VALUES (40, N'Vieux', 4.5, 10)
INSERT INTO [dbo].[Menu_Item] ([ItemID], [naam], [prijs], [aantal]) VALUES (41, N'Berenburg', 3.5, 20)
INSERT INTO [dbo].[Menu_Item] ([ItemID], [naam], [prijs], [aantal]) VALUES (42, N'Koffie', 2.5, 30)
INSERT INTO [dbo].[Menu_Item] ([ItemID], [naam], [prijs], [aantal]) VALUES (43, N'Cappuchino', 3.5, 40)
INSERT INTO [dbo].[Menu_Item] ([ItemID], [naam], [prijs], [aantal]) VALUES (44, N'Espresso', 3, 25)
INSERT INTO [dbo].[Menu_Item] ([ItemID], [naam], [prijs], [aantal]) VALUES (45, N'Thee', 2.5, 34)